### ISSUE TITLE
Frequency of root node is not calculated

### ISSUE THREAD

**Issue by rlindsberg** [rlindsberg/1019ID-Programming-II#5]
https://github.com/rlindsberg/1019ID-Programming-II/blob/99c03ef88b235ca3407b20eee7e58edd4cb5b216/exercise/huffman.ex#L66-L69

```
iex(140)> {:node, child_node, child_leaf, freq} = Huffman.tree(Huffman.sample)                                                                                                                                  
** (MatchError) no match of right hand side value: {:node, {:node, {:node, {:node, {:node, {:leaf, "z", 1}, {:leaf, "y", 2}, 3}, {:leaf, "x", 5}, 8}, {:leaf, "f", 7}, 15}, {:leaf, "e", 10}, 25}, {:leaf, " ", 15}}
    (stdlib) erl_eval.erl:453: :erl_eval.expr/5
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
```

**Comment by rlindsberg** [comment]
Confirmed bug. The root node should have fred 40.
